### ISSUE TITLE
Rust and Node Version Problem

### ISSUE THREAD

**Issue by bitman09** [solguru310/solana-mpl-core-nft-staking#4]
I've already tried to run this project but couldn't do that.
I got dependencies version issue.
Can you provide me the solutions to fix?

**Comment by solguru310** [comment]
Interesting!!
Yes, Great quiz.
To run the Anchor project, dependencies version problem is very important.
If you are available now, I'll explain more details via meeting.
Looking forward to hearing from you.

**Comment by bitman09** [comment]
Sounds great.
Okay, we can take a meeting right now.
Thanks for your help.
